--
-- PostgreSQL database dump
--

-- Dumped from database version 14.15 (Debian 14.15-1.pgdg120+1)
-- Dumped by pg_dump version 16.9 (Ubuntu 16.9-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: development_user
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO development_user;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: goose_db_version; Type: TABLE; Schema: public; Owner: development_user
--

CREATE TABLE public.goose_db_version (
    id integer NOT NULL,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.goose_db_version OWNER TO development_user;

--
-- Name: goose_db_version_id_seq; Type: SEQUENCE; Schema: public; Owner: development_user
--

ALTER TABLE public.goose_db_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goose_db_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory_items; Type: TABLE; Schema: public; Owner: development_user
--

CREATE TABLE public.inventory_items (
    id uuid NOT NULL,
    product_id uuid,
    inventory_location_id uuid,
    quantity_in_location integer,
    product_uom_id uuid
);


ALTER TABLE public.inventory_items OWNER TO development_user;

--
-- Name: inventory_locations; Type: TABLE; Schema: public; Owner: development_user
--

CREATE TABLE public.inventory_locations (
    id uuid NOT NULL,
    location character varying(100),
    barcode text
);


ALTER TABLE public.inventory_locations OWNER TO development_user;

--
-- Name: inventory_transactions; Type: TABLE; Schema: public; Owner: development_user
--

CREATE TABLE public.inventory_transactions (
    id uuid NOT NULL,
    transaction_timestamp timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    inventory_location_id uuid,
    product_id uuid,
    product_uom uuid,
    transaction_amount integer
);


ALTER TABLE public.inventory_transactions OWNER TO development_user;

--
-- Name: COLUMN inventory_transactions.transaction_amount; Type: COMMENT; Schema: public; Owner: development_user
--

COMMENT ON COLUMN public.inventory_transactions.transaction_amount IS 'Can be either negative or positive.';


--
-- Name: order_items; Type: TABLE; Schema: public; Owner: development_user
--

CREATE TABLE public.order_items (
    id uuid NOT NULL,
    order_id uuid,
    quantity integer,
    total_price real
);


ALTER TABLE public.order_items OWNER TO development_user;

--
-- Name: orders; Type: TABLE; Schema: public; Owner: development_user
--

CREATE TABLE public.orders (
    id uuid NOT NULL,
    order_total real,
    tax_amount real,
    final_total real,
    completed boolean
);


ALTER TABLE public.orders OWNER TO development_user;

--
-- Name: product_categories; Type: TABLE; Schema: public; Owner: development_user
--

CREATE TABLE public.product_categories (
    id uuid NOT NULL,
    category character varying(40),
    category_info text
);


ALTER TABLE public.product_categories OWNER TO development_user;

--
-- Name: product_uoms; Type: TABLE; Schema: public; Owner: development_user
--

CREATE TABLE public.product_uoms (
    id uuid NOT NULL,
    product_id uuid,
    uom_id uuid,
    parent_uom_id uuid,
    senior_uom boolean DEFAULT false,
    has_child_uom boolean DEFAULT false,
    parent_uom_qantity_multiplier integer,
    purchasing_cost real,
    uom_barcode text
);


ALTER TABLE public.product_uoms OWNER TO development_user;

--
-- Name: COLUMN product_uoms.senior_uom; Type: COMMENT; Schema: public; Owner: development_user
--

COMMENT ON COLUMN public.product_uoms.senior_uom IS 'The largest unit of measurement we purchase in.';


--
-- Name: COLUMN product_uoms.parent_uom_qantity_multiplier; Type: COMMENT; Schema: public; Owner: development_user
--

COMMENT ON COLUMN public.product_uoms.parent_uom_qantity_multiplier IS '
  The quantity of the current product_uom that come in the parent_uom.  
  For exampe selling soda cans: Pallets have 100 boxes, each box has twelve cans.
';


--
-- Name: products; Type: TABLE; Schema: public; Owner: development_user
--

CREATE TABLE public.products (
    id uuid NOT NULL,
    product_category_id uuid,
    supplier_id uuid,
    cost real,
    selling real,
    name character varying(40),
    barcode text
);


ALTER TABLE public.products OWNER TO development_user;

--
-- Name: suppliers; Type: TABLE; Schema: public; Owner: development_user
--

CREATE TABLE public.suppliers (
    id uuid NOT NULL,
    supplier_name character varying(100)
);


ALTER TABLE public.suppliers OWNER TO development_user;

--
-- Name: total_allocated_products; Type: TABLE; Schema: public; Owner: development_user
--

CREATE TABLE public.total_allocated_products (
    id uuid NOT NULL,
    product_id uuid,
    allocated integer,
    available integer
);


ALTER TABLE public.total_allocated_products OWNER TO development_user;

--
-- Name: total_product_in_inventory; Type: TABLE; Schema: public; Owner: development_user
--

CREATE TABLE public.total_product_in_inventory (
    id uuid NOT NULL,
    product_id uuid,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    total_product_on_hand integer
);


ALTER TABLE public.total_product_in_inventory OWNER TO development_user;

--
-- Name: units_of_measurements; Type: TABLE; Schema: public; Owner: development_user
--

CREATE TABLE public.units_of_measurements (
    id uuid NOT NULL,
    uom_name character varying(40) NOT NULL,
    uom_abbreviation character varying(4)
);


ALTER TABLE public.units_of_measurements OWNER TO development_user;

--
-- Name: users; Type: TABLE; Schema: public; Owner: development_user
--

CREATE TABLE public.users (
    id uuid NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    name character varying(40)
);


ALTER TABLE public.users OWNER TO development_user;

--
-- Name: goose_db_version goose_db_version_pkey; Type: CONSTRAINT; Schema: public; Owner: development_user
--

ALTER TABLE ONLY public.goose_db_version
    ADD CONSTRAINT goose_db_version_pkey PRIMARY KEY (id);


--
-- Name: inventory_items inventory_items_pkey; Type: CONSTRAINT; Schema: public; Owner: development_user
--

ALTER TABLE ONLY public.inventory_items
    ADD CONSTRAINT inventory_items_pkey PRIMARY KEY (id);


--
-- Name: inventory_locations inventory_locations_pkey; Type: CONSTRAINT; Schema: public; Owner: development_user
--

ALTER TABLE ONLY public.inventory_locations
    ADD CONSTRAINT inventory_locations_pkey PRIMARY KEY (id);


--
-- Name: inventory_transactions inventory_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: development_user
--

ALTER TABLE ONLY public.inventory_transactions
    ADD CONSTRAINT inventory_transactions_pkey PRIMARY KEY (id);


--
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: development_user
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: development_user
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: product_categories product_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: development_user
--

ALTER TABLE ONLY public.product_categories
    ADD CONSTRAINT product_categories_pkey PRIMARY KEY (id);


--
-- Name: product_uoms product_uoms_pkey; Type: CONSTRAINT; Schema: public; Owner: development_user
--

ALTER TABLE ONLY public.product_uoms
    ADD CONSTRAINT product_uoms_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: development_user
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: suppliers suppliers_pkey; Type: CONSTRAINT; Schema: public; Owner: development_user
--

ALTER TABLE ONLY public.suppliers
    ADD CONSTRAINT suppliers_pkey PRIMARY KEY (id);


--
-- Name: total_allocated_products total_allocated_products_pkey; Type: CONSTRAINT; Schema: public; Owner: development_user
--

ALTER TABLE ONLY public.total_allocated_products
    ADD CONSTRAINT total_allocated_products_pkey PRIMARY KEY (id);


--
-- Name: total_product_in_inventory total_product_in_inventory_pkey; Type: CONSTRAINT; Schema: public; Owner: development_user
--

ALTER TABLE ONLY public.total_product_in_inventory
    ADD CONSTRAINT total_product_in_inventory_pkey PRIMARY KEY (id);


--
-- Name: units_of_measurements units_of_measurements_pkey; Type: CONSTRAINT; Schema: public; Owner: development_user
--

ALTER TABLE ONLY public.units_of_measurements
    ADD CONSTRAINT units_of_measurements_pkey PRIMARY KEY (id);


--
-- Name: units_of_measurements units_of_measurements_uom_name_key; Type: CONSTRAINT; Schema: public; Owner: development_user
--

ALTER TABLE ONLY public.units_of_measurements
    ADD CONSTRAINT units_of_measurements_uom_name_key UNIQUE (uom_name);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: development_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: inventory_items inventory_items_inventory_location_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: development_user
--

ALTER TABLE ONLY public.inventory_items
    ADD CONSTRAINT inventory_items_inventory_location_id_fkey FOREIGN KEY (inventory_location_id) REFERENCES public.inventory_locations(id);


--
-- Name: inventory_items inventory_items_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: development_user
--

ALTER TABLE ONLY public.inventory_items
    ADD CONSTRAINT inventory_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: inventory_items inventory_items_product_uom_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: development_user
--

ALTER TABLE ONLY public.inventory_items
    ADD CONSTRAINT inventory_items_product_uom_id_fkey FOREIGN KEY (product_uom_id) REFERENCES public.product_uoms(id);


--
-- Name: inventory_transactions inventory_transactions_inventory_location_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: development_user
--

ALTER TABLE ONLY public.inventory_transactions
    ADD CONSTRAINT inventory_transactions_inventory_location_id_fkey FOREIGN KEY (inventory_location_id) REFERENCES public.inventory_locations(id);


--
-- Name: order_items order_items_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: development_user
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: product_uoms product_uoms_parent_uom_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: development_user
--

ALTER TABLE ONLY public.product_uoms
    ADD CONSTRAINT product_uoms_parent_uom_id_fkey FOREIGN KEY (parent_uom_id) REFERENCES public.units_of_measurements(id);


--
-- Name: product_uoms product_uoms_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: development_user
--

ALTER TABLE ONLY public.product_uoms
    ADD CONSTRAINT product_uoms_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: product_uoms product_uoms_uom_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: development_user
--

ALTER TABLE ONLY public.product_uoms
    ADD CONSTRAINT product_uoms_uom_id_fkey FOREIGN KEY (uom_id) REFERENCES public.units_of_measurements(id);


--
-- Name: products products_product_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: development_user
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_product_category_id_fkey FOREIGN KEY (product_category_id) REFERENCES public.product_categories(id);


--
-- Name: total_allocated_products total_allocated_products_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: development_user
--

ALTER TABLE ONLY public.total_allocated_products
    ADD CONSTRAINT total_allocated_products_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: total_product_in_inventory total_product_in_inventory_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: development_user
--

ALTER TABLE ONLY public.total_product_in_inventory
    ADD CONSTRAINT total_product_in_inventory_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: development_user
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

